# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LMTool_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.imageTab = GraphicsLayoutWidget()
        self.imageTab.setObjectName("imageTab")
        self.tabs.addTab(self.imageTab, "")
        self.plot = PlotWidget()
        self.plot.setObjectName("plot")
        self.tabs.addTab(self.plot, "")
        self.fitTab = GraphicsLayoutWidget()
        self.fitTab.setObjectName("fitTab")
        self.tabs.addTab(self.fitTab, "")
        self.verticalLayout.addWidget(self.tabs)
        self.parameterFrame = QtWidgets.QFrame(self.centralwidget)
        self.parameterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameterFrame.setObjectName("parameterFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.parameterFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.wavelength = QParameterWidget(self.parameterFrame)
        self.wavelength.setObjectName("wavelength")
        self.gridLayout.addWidget(self.wavelength, 0, 0, 1, 1)
        self.magnification = QParameterWidget(self.parameterFrame)
        self.magnification.setObjectName("magnification")
        self.gridLayout.addWidget(self.magnification, 0, 1, 1, 1)
        self.n_m = QParameterWidget(self.parameterFrame)
        self.n_m.setObjectName("n_m")
        self.gridLayout.addWidget(self.n_m, 0, 2, 1, 1)
        self.a_p = QParameterWidget(self.parameterFrame)
        self.a_p.setObjectName("a_p")
        self.gridLayout.addWidget(self.a_p, 1, 0, 1, 1)
        self.n_p = QParameterWidget(self.parameterFrame)
        self.n_p.setObjectName("n_p")
        self.gridLayout.addWidget(self.n_p, 1, 1, 1, 1)
        self.k_p = QParameterWidget(self.parameterFrame)
        self.k_p.setObjectName("k_p")
        self.gridLayout.addWidget(self.k_p, 1, 2, 1, 1)
        self.x_p = QParameterWidget(self.parameterFrame)
        self.x_p.setObjectName("x_p")
        self.gridLayout.addWidget(self.x_p, 2, 0, 1, 1)
        self.y_p = QParameterWidget(self.parameterFrame)
        self.y_p.setObjectName("y_p")
        self.gridLayout.addWidget(self.y_p, 2, 1, 1, 1)
        self.z_p = QParameterWidget(self.parameterFrame)
        self.z_p.setObjectName("z_p")
        self.gridLayout.addWidget(self.z_p, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.parameterFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Parameters = QtWidgets.QAction(MainWindow)
        self.actionSave_Parameters.setObjectName("actionSave_Parameters")
        self.actionSave_Parameters_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Parameters_As.setObjectName("actionSave_Parameters_As")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_Parameters)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LMTool"))
        self.tabs.setTabText(self.tabs.indexOf(self.imageTab), _translate("MainWindow", "image"))
        self.tabs.setTabText(self.tabs.indexOf(self.plot), _translate("MainWindow", "profile"))
        self.tabs.setTabText(self.tabs.indexOf(self.fitTab), _translate("MainWindow", "fit"))
        self.wavelength.setStatusTip(_translate("MainWindow", "Wavelength of illumination [micrometers]"))
        self.magnification.setStatusTip(_translate("MainWindow", "Magnification [micrometers/pixel]"))
        self.n_m.setStatusTip(_translate("MainWindow", "Refractive index of medium"))
        self.a_p.setStatusTip(_translate("MainWindow", "Radius of particle [micrometers]"))
        self.n_p.setStatusTip(_translate("MainWindow", "Refractive index of particle"))
        self.k_p.setStatusTip(_translate("MainWindow", "Absorption coefficient of particle"))
        self.x_p.setStatusTip(_translate("MainWindow", "x coordinate [pixel]"))
        self.y_p.setStatusTip(_translate("MainWindow", "y coordinate [pixel]"))
        self.z_p.setStatusTip(_translate("MainWindow", "Axial position of particle [pixel]"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionOpen.setText(_translate("MainWindow", "Open ..."))
        self.actionSave_Parameters.setText(_translate("MainWindow", "Save Parameters ..."))
        self.actionSave_Parameters_As.setText(_translate("MainWindow", "Save Parameters As ..."))

from QParameterWidget import QParameterWidget
from pyqtgraph import GraphicsLayoutWidget, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

